version: '3'
services:
  presentable-sql-db:
    image: postgres:12
    restart: always
    ports:
      - 5444:5432
    environment:
      POSTGRES_PASSWORD: as180401
      POSTGRES_USER: aleksey
      POSTGRES_DB: presentable