version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgresql_db
    links:
      - postgresql_db:app_db
  postgresql_db:
    image: postgres:12
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DATABASE: presentable
      POSTGRES_USER: aleksey
      POSTGRES_PASSWORD: aleksey
      POSTGRES_ROOT_PASSWORD: aleksey
      POSTGRES_HOST_AUTH_METHOD: trust
#  mongo-presentable-db:
#    container_name: "mongo-presentable-db"
#    image: mongo:latest
#    ports:
#      - 27027:27017
#    environment:
#      MONGO_DB: Slides
