spring:
  data:
    mongodb:
      database: Slides
      port: 27017
      host: localhost
  datasource:
    url: jdbc:postgresql://localhost:5432/presentable
    username: aleksey
    password: aleksey
